dataset_source_name: webcam
dataset_target_name: amazon
train_only_source: False
train_only_target: False
continue_optimizer: True
keep_source: 4
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.2
base_model_path: 'webcam_source/model_final.pth'
base_optim_path: 'webcam_source/optim_final.pth'

