dataset_name: amazon
train_only_source: True
train_only_target: False
steps_per_epoch: 250
num_epochs: 25
batch_size: 16
model:
  func: resnet50
  pretrained: True
  as_class: True
fc:
  func: Linear
  in_features: 2048
  out_features: 31
  as_class: True
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.0005
