dataset_source_name: webcam
dataset_target_name: amazon
train_only_source: False
train_only_target: False
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.0005
base_model_path: 'webcam_source/model_final.pth'

