train_only_source: False
train_only_target: True
freeze_func:
  func: freeze_model
  exclude_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.0005


