dataset_source_name: amazon
dataset_target_name: webcam
train_only_source: False
train_only_target: True
continue_optimizer: True
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.9
base_model_path: 'amazon_source/model_final.pth'
base_optim_path: 'amazon_source/optim_final.pth'

