dataset_source_name: amazon
dataset_target_name: webcam
train_only_source: False
train_only_target: True
continue_optimizer: True
steps_per_epoch: 200
num_epochs: 20
batch_size: 16
model:
  func: resnet50
  pretrained: False
  as_class: True
fc:
  func: Linear
  in_features: 2048
  out_features: 31
  as_class: True
optimizer:
  func: SGD
lr: 0.0001
momentum: 0.9
base_model_path: 'amazon_source/model_final.pth'
base_optim_path: 'amazon_source/optim_final.pth'

